### ISSUE TITLE
Prisma generator either gets stuck or throws a ENOENT

### ISSUE THREAD

**Issue by jessielaf** [chrishoermann/zod-prisma-types#64]
Hi,

Thanks for this library. I have been trying to setup type generation for prisma. But most of them do not work except for `zod-prisma`. However, this library is not supported (thats how I found this library). The command `npx prisma generator` either gets stuck or throws an erorr. The error thrown:

```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: spawn zod-prisma-types ENOENT
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I now it means that it cannot access something but it is not clear what. Have you experienced this issue before?

Versions:
- prisma: 4.8.1
- zod: 3.20.2
- zod-prisma-types: 1.6.8

**Comment by chrishoermann** [comment]
@jessielaf that means that somewhere in the generator code there ist a problem. Please revert back to v1.6.7 and see if the issued persists. I'll Look into this.

**Comment by jessielaf** [comment]
@chrishoermann I have just tried 1.6.7 and still getting `Error: spawn zod-prisma-types ENOENT`. I think it may be something in my configuration, but I cannot figure out what. What version of prisma are you using?

I have turned on debug for prisma. See the output of prisma generate command below:

```
  prisma:engines  binaries to download libquery-engine, migration-engine, introspection-engine, prisma-fmt +0ms
  prisma:loadEnv  project root found at C:\Users\Jessie\projects\boiler\boiler-new\package.json +0ms
  prisma:tryLoadEnv  Environment variables loaded from C:\Users\Jessie\projects\boiler\boiler-new\.env +0ms
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
  prisma:getConfig  Using getConfig Wasm +0ms
  prisma:getConfig  config data retrieved without errors in getConfig Wasm +6ms
  prisma:getDMMF  Using CLI Query Engine (Node-API Library) at: C:\Users\Jessie\projects\boiler\boiler-new\node_modules\prisma\query_engine-windows.dll.node +0ms
  prisma:getDMMF  Loaded Node-API Library +11ms
  prisma:getDMMF  unserialized dmmf result ready +11ms
  prisma:getDMMF  dmmf retrieved without errors in getDmmfNodeAPI +3ms
  prisma:generator  prismaCLIDir C:\Users\Jessie\projects\boiler\boiler-new\node_modules\prisma +0ms
  prisma:generator  prismaClientDir C:\Users\Jessie\projects\boiler\boiler-new\node_modules\@prisma\client +1ms
  prisma:generator  baseDir C:\Users\Jessie\projects\boiler\boiler-new\prisma +0ms
  prisma:generator  typescriptPath C:\Users\Jessie\projects\boiler\boiler-new\node_modules\typescript +9ms
  prisma:GeneratorProcess  node:internal/modules/cjs/loader:417 +0ms
  prisma:GeneratorProcess        throw err; +1ms
  prisma:GeneratorProcess        ^ +0ms
  prisma:GeneratorProcess  Error: Cannot find module 'C:\Users\Jessie\projects\boiler\boiler-new\node_modules\@prisma\debug\dist\index.js'. Please verify that the package.json has a valid "main" entry +1ms
  prisma:GeneratorProcess      at tryPackage (node:internal/modules/cjs/loader:409:19) +0ms
  prisma:GeneratorProcess      at Module._findPath (node:internal/modules/cjs/loader:651:18) +1ms
  prisma:GeneratorProcess      at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27) +0ms
  prisma:GeneratorProcess      at Module._load (node:internal/modules/cjs/loader:885:27) +1ms
  prisma:GeneratorProcess      at Module.require (node:internal/modules/cjs/loader:1105:19) +0ms
  prisma:GeneratorProcess      at require (node:internal/modules/cjs/helpers:103:18) +1ms
  prisma:GeneratorProcess      at Object.<anonymous> (C:\Users\Jessie\projects\boiler\boiler-new\node_modules\@prisma\generator-helper\dist\GeneratorProcess.js:32:28) +0ms
  prisma:GeneratorProcess      at Module._compile (node:internal/modules/cjs/loader:1218:14) +0ms
  prisma:GeneratorProcess      at Module._extensions..js (node:internal/modules/cjs/loader:1272:10) +1ms
  prisma:GeneratorProcess      at Module.load (node:internal/modules/cjs/loader:1081:32) { +0ms
  prisma:GeneratorProcess    code: 'MODULE_NOT_FOUND', +0ms
  prisma:GeneratorProcess    path: 'C:\\Users\\Jessie\\projects\\boiler\\boiler-new\\node_modules\\@prisma\\debug\\package.json', +1ms       
  prisma:GeneratorProcess    requestPath: '@prisma/debug' +0ms
  prisma:GeneratorProcess  } +0ms
  prisma:GeneratorProcess  Node.js v18.13.0 +1ms
  prisma:GeneratorProcess  2023-01-26T07:58:53.732Z prisma:client:generator  requiredEngine: libqueryEngine +90ms
Error: Error: spawn zod-prisma-types ENOENT
    at notFoundError (C:\Users\Jessie\projects\boiler\boiler-new\node_modules\prisma\build\index.js:3004:28)
    at verifyENOENT (C:\Users\Jessie\projects\boiler\boiler-new\node_modules\prisma\build\index.js:3031:16)
    at cp2.emit (C:\Users\Jessie\projects\boiler\boiler-new\node_modules\prisma\build\index.js:3020:23)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

**Comment by chrishoermann** [comment]
@jessielaf did you find a solution to this? I used Prisma version 4.9.

**Comment by chrishoermann** [comment]
closing since it seems that this is not a problem with the generator.

**Comment by jessielaf** [comment]
@chrishoermann sorry for the late response. I did not have time to explore this yet, but I think it has something to do with Prisma.
